version: '2'
networks:
  api:
    driver: "bridge"
services: 
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    ports:
        - 8080:8080
        - 8000:8000
    volumes: 
      - ./backend:/app/home
    tty: true
    networks: 
      - api