export enum DINOSAUR {
    FIRST_SPRITE = 1335,
    DEFAULT_HEIGHT = 88,
    DEFAULT_WIDTH = 98,
    NORMAL = DINOSAUR.FIRST_SPRITE + 3,
    CLOSED_EYE = DINOSAUR.FIRST_SPRITE + DINOSAUR.DEFAULT_WIDTH - 7,
    LEFT_LEG_UP = DINOSAUR.FIRST_SPRITE + 2 * DINOSAUR.DEFAULT_WIDTH - 17,
    RIGHT_LEG_UP = DINOSAUR.FIRST_SPRITE + 3 * DINOSAUR.DEFAULT_WIDTH - 27,
    BIG_EYE_BORDER = DINOSAUR.FIRST_SPRITE + 4 *  DINOSAUR.DEFAULT_WIDTH - 37,
    BIG_EYE_NO_BORDER = DINOSAUR.FIRST_SPRITE + 5 * DINOSAUR.DEFAULT_WIDTH - 47
}